import type { GLAccount, TaxCode } from "./types";

// ─── Account Category Config ────────────────────────────────────────────────
export const ACCOUNT_CATEGORY_CONFIG = [
  {
    value: "asset" as const,
    label: "Assets",
    range: "100000 – 199999",
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-500/10",
    badgeColor:
      "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/20",
  },
  {
    value: "liability" as const,
    label: "Liabilities",
    range: "200000 – 299999",
    color: "text-rose-600 dark:text-rose-400",
    bgColor: "bg-rose-500/10",
    badgeColor:
      "bg-rose-500/15 text-rose-700 dark:text-rose-300 border-rose-500/20",
  },
  {
    value: "equity" as const,
    label: "Equity",
    range: "300000 – 399999",
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-500/10",
    badgeColor:
      "bg-blue-500/15 text-blue-700 dark:text-blue-300 border-blue-500/20",
  },
  {
    value: "income" as const,
    label: "Income",
    range: "400000 – 499999",
    color: "text-violet-600 dark:text-violet-400",
    bgColor: "bg-violet-500/10",
    badgeColor:
      "bg-violet-500/15 text-violet-700 dark:text-violet-300 border-violet-500/20",
  },
  {
    value: "expense" as const,
    label: "Expenses",
    range: "500000 – 599999",
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-500/10",
    badgeColor:
      "bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/20",
  },
] as const;

// ─── Account Type Options ────────────────────────────────────────────────────
export const ACCOUNT_TYPE_OPTIONS = [
  { value: "ledger", label: "Ledger" },
  { value: "customer", label: "Customer" },
  { value: "vendor", label: "Vendor" },
] as const;

// ─── Posting Type Options ────────────────────────────────────────────────────
export const POSTING_TYPE_OPTIONS = [
  { value: "header", label: "Header (Non-postable)" },
  { value: "posting", label: "Posting (Transactional)" },
] as const;

// ─── Dimension Type Options ──────────────────────────────────────────────────
export const DIMENSION_TYPE_OPTIONS = [
  {
    value: "cost-center",
    label: "Cost Center",
    description: "Track costs by business unit or function",
    icon: "Building2",
  },
  {
    value: "project",
    label: "Project",
    description: "Allocate revenue/expenses to specific projects",
    icon: "FolderKanban",
  },
  {
    value: "property",
    label: "Property",
    description: "Track transactions per real estate asset",
    icon: "Home",
  },
  {
    value: "department",
    label: "Department",
    description: "Segment by organizational department",
    icon: "Users",
  },
] as const;

// ─── Tax Code Type Options ───────────────────────────────────────────────────
export const TAX_CODE_TYPE_OPTIONS = [
  { value: "input", label: "Input VAT" },
  { value: "output", label: "Output VAT" },
  { value: "exempt", label: "Exempt" },
] as const;

// ─── Default Chart of Accounts (Seed Data) ──────────────────────────────────
export const DEFAULT_CHART_OF_ACCOUNTS: GLAccount[] = [
  // ── Assets (100000 Series) ──
  {
    accountNumber: "100000",
    accountName: "Assets",
    accountType: "ledger",
    accountCategory: "asset",
    postingType: "header",
    parentAccountNumber: null,
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "110000",
    accountName: "Current Assets",
    accountType: "ledger",
    accountCategory: "asset",
    postingType: "header",
    parentAccountNumber: "100000",
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "111000",
    accountName: "Cash",
    accountType: "ledger",
    accountCategory: "asset",
    postingType: "posting",
    parentAccountNumber: "110000",
    allowManualEntry: true,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "112000",
    accountName: "Bank",
    accountType: "ledger",
    accountCategory: "asset",
    postingType: "posting",
    parentAccountNumber: "110000",
    allowManualEntry: true,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "113000",
    accountName: "Accounts Receivable",
    accountType: "customer",
    accountCategory: "asset",
    postingType: "posting",
    parentAccountNumber: "110000",
    allowManualEntry: true,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "114000",
    accountName: "VAT Input Recoverable",
    accountType: "ledger",
    accountCategory: "asset",
    postingType: "posting",
    parentAccountNumber: "110000",
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "120000",
    accountName: "Non-Current Assets",
    accountType: "ledger",
    accountCategory: "asset",
    postingType: "header",
    parentAccountNumber: "100000",
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "121000",
    accountName: "Fixed Assets",
    accountType: "ledger",
    accountCategory: "asset",
    postingType: "posting",
    parentAccountNumber: "120000",
    allowManualEntry: true,
    mandatoryDimensions: true,
    linkedDimensions: ["cost-center"],
    isActive: true,
  },

  // ── Liabilities (200000 Series) ──
  {
    accountNumber: "200000",
    accountName: "Liabilities",
    accountType: "ledger",
    accountCategory: "liability",
    postingType: "header",
    parentAccountNumber: null,
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "210000",
    accountName: "Current Liabilities",
    accountType: "ledger",
    accountCategory: "liability",
    postingType: "header",
    parentAccountNumber: "200000",
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "211000",
    accountName: "Accounts Payable",
    accountType: "vendor",
    accountCategory: "liability",
    postingType: "posting",
    parentAccountNumber: "210000",
    allowManualEntry: true,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "212000",
    accountName: "VAT Output Payable",
    accountType: "ledger",
    accountCategory: "liability",
    postingType: "posting",
    parentAccountNumber: "210000",
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },

  // ── Equity (300000 Series) ──
  {
    accountNumber: "300000",
    accountName: "Equity",
    accountType: "ledger",
    accountCategory: "equity",
    postingType: "header",
    parentAccountNumber: null,
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "310000",
    accountName: "Share Capital",
    accountType: "ledger",
    accountCategory: "equity",
    postingType: "posting",
    parentAccountNumber: "300000",
    allowManualEntry: true,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "320000",
    accountName: "Retained Earnings",
    accountType: "ledger",
    accountCategory: "equity",
    postingType: "posting",
    parentAccountNumber: "300000",
    allowManualEntry: true,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },

  // ── Income (400000 Series) ──
  {
    accountNumber: "400000",
    accountName: "Revenue",
    accountType: "ledger",
    accountCategory: "income",
    postingType: "header",
    parentAccountNumber: null,
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "410000",
    accountName: "Sales Revenue",
    accountType: "ledger",
    accountCategory: "income",
    postingType: "posting",
    parentAccountNumber: "400000",
    allowManualEntry: true,
    mandatoryDimensions: true,
    linkedDimensions: ["cost-center", "project"],
    isActive: true,
  },
  {
    accountNumber: "420000",
    accountName: "Service Income",
    accountType: "ledger",
    accountCategory: "income",
    postingType: "posting",
    parentAccountNumber: "400000",
    allowManualEntry: true,
    mandatoryDimensions: true,
    linkedDimensions: ["cost-center", "project"],
    isActive: true,
  },

  // ── Expenses (500000 Series) ──
  {
    accountNumber: "500000",
    accountName: "Expenses",
    accountType: "ledger",
    accountCategory: "expense",
    postingType: "header",
    parentAccountNumber: null,
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "510000",
    accountName: "Direct Expenses",
    accountType: "ledger",
    accountCategory: "expense",
    postingType: "header",
    parentAccountNumber: "500000",
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "511000",
    accountName: "Cost of Goods Sold",
    accountType: "ledger",
    accountCategory: "expense",
    postingType: "posting",
    parentAccountNumber: "510000",
    allowManualEntry: true,
    mandatoryDimensions: true,
    linkedDimensions: ["cost-center"],
    isActive: true,
  },
  {
    accountNumber: "520000",
    accountName: "Operating Expenses",
    accountType: "ledger",
    accountCategory: "expense",
    postingType: "header",
    parentAccountNumber: "500000",
    allowManualEntry: false,
    mandatoryDimensions: false,
    linkedDimensions: [],
    isActive: true,
  },
  {
    accountNumber: "521000",
    accountName: "Rent Expense",
    accountType: "ledger",
    accountCategory: "expense",
    postingType: "posting",
    parentAccountNumber: "520000",
    allowManualEntry: true,
    mandatoryDimensions: true,
    linkedDimensions: ["cost-center", "property"],
    isActive: true,
  },
  {
    accountNumber: "522000",
    accountName: "Salaries Expense",
    accountType: "ledger",
    accountCategory: "expense",
    postingType: "posting",
    parentAccountNumber: "520000",
    allowManualEntry: true,
    mandatoryDimensions: true,
    linkedDimensions: ["cost-center", "department"],
    isActive: true,
  },
];

// ─── Default Tax Codes (UAE VAT) ─────────────────────────────────────────────
export const DEFAULT_TAX_CODES: TaxCode[] = [
  {
    id: "tc-1",
    code: "SR",
    name: "Standard Rate",
    rate: 5,
    type: "output",
    inputVatAccount: "114000",
    outputVatAccount: "212000",
    isActive: true,
  },
  {
    id: "tc-2",
    code: "ZR",
    name: "Zero Rated",
    rate: 0,
    type: "output",
    inputVatAccount: "114000",
    outputVatAccount: "212000",
    isActive: true,
  },
  {
    id: "tc-3",
    code: "EX",
    name: "Exempt",
    rate: 0,
    type: "exempt",
    inputVatAccount: "",
    outputVatAccount: "",
    isActive: true,
  },
];

// ─── GL Posting Rules ────────────────────────────────────────────────────────
export const GL_POSTING_RULES = [
  {
    id: "rule-1",
    title: "Double-Entry Accounting",
    description:
      "Every transaction must have equal debit and credit amounts. The sum of all debits must equal the sum of all credits to maintain the accounting equation.",
    icon: "Scale",
    severity: "critical" as const,
  },
  {
    id: "rule-2",
    title: "Header Accounts Non-Postable",
    description:
      "Header accounts are used for grouping and reporting purposes only. Direct postings can only be made to accounts with Posting type.",
    icon: "ShieldAlert",
    severity: "critical" as const,
  },
  {
    id: "rule-3",
    title: "Pre-Posting Validation",
    description:
      "All transactions must pass validation checks before posting. This includes account status verification, dimension requirements, and balance validation.",
    icon: "CheckCircle2",
    severity: "warning" as const,
  },
  {
    id: "rule-4",
    title: "Audit Trail Mandatory",
    description:
      "Every posting generates an immutable audit trail entry. All changes to GL entries are tracked with user, timestamp, and modification details.",
    icon: "FileSearch",
    severity: "info" as const,
  },
  {
    id: "rule-5",
    title: "Dimension Linking",
    description:
      "Transactions and GL entries can be linked to dimensions (Cost Center, Project, Property, Department) for analytical reporting without creating excessive accounts.",
    icon: "Layers",
    severity: "info" as const,
  },
];
